version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfl_rushing_dev
    volumes:
      - ./data/db:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: nfl_rushing_dev
      PGPORT: 5432
      PGHOST: postgres
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    command: sh -c "cd /server && mix deps.get && mix ecto.reset && mix phx.server"
    tty: true
    stdin_open: true
    volumes:
      - ./server:/server
  client:
    build:
      context: ./client
      args:
        REACT_APP_API_DEV: http://127.0.0.1:4000/
    command: sh -c "cd /client && npm start"
    volumes:
      - ./client/node_modules
      - ./client:/client
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
