version: '3.8'

services:
  server:
    build:
      context: ./server
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: nfl_rushing_dev
      PGPORT: 5432
      PGHOST: postgres
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    command: sh -c "mix ecto.setup && mix phx.server"
    volumes:
      - .:/app
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfl_rushing_dev
    volumes:
      - ./data/db:/var/lib/postgresql/data
